"""empty message

Revision ID: b48db1d20225
Revises: 0763d677d453
Create Date: 2025-08-23 03:34:21.072155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48db1d20225'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_mascota', sa.String(length=120), nullable=False),
    sa.Column('peso_mascota', sa.Float(), nullable=False),
    sa.Column('color_mascota', sa.String(length=120), nullable=False),
    sa.Column('especie', sa.String(length=120), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=False),
    sa.Column('nombre_veterinario', sa.String(length=120), nullable=False),
    sa.Column('fecha_atencion', sa.Date(), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=False),
    sa.Column('tratamiento', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_dueno', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('nombre_dueno')

    op.drop_table('receta')
    # ### end Alembic commands ###
